# -*- coding: utf-8 -*-
"""Obesity Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Yd2PCcKRTdUb55qHVdaqvEflY75uKKY
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import pickle

# Carregar os dados
data = pd.read_csv('Obesity prediction.csv')

# Verificar valores ausentes
print("Valores ausentes por coluna:")
print(data.isnull().sum())

# Preenchendo valores ausentes (se necessário)
data = data.dropna()  # Remover linhas com valores ausentes (ajustável)

# Remover colunas de baixa importância
columns_to_drop = ["SMOKE", "SCC", "FAVC"]
data = data.drop(columns=columns_to_drop)

# Arredondar valores flutuantes
num_cols = ['Age', 'Height', 'Weight', 'CH2O', 'FAF', 'TUE']
data[num_cols] = data[num_cols].round(0)

# Codificar variáveis categóricas
label_encoders = {}
for column in data.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    data[column] = le.fit_transform(data[column])
    label_encoders[column] = le
    
names = {
    0: "Peso Insuficiente",
    1: "Peso Normal",
    2: "Sobrepeso Nível I",
    3: "Sobrepeso Nível II",
    4: "Obesidade Tipo I",
    5: "Obesidade Tipo II",
    6: "Obesidade Tipo III"
}

# Salvando o dicionário em um arquivo .pkl
with open("names.pkl", "wb") as f:
    pickle.dump(names, f)

print("Arquivo names.pkl criado com sucesso!")

# Separar features e target
X = data.drop('Obesity', axis=1)
y = data['Obesity']

# Dividir em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Treinar o modelo Random Forest
rf_model = RandomForestClassifier(random_state=42, n_estimators=100)
rf_model.fit(X_train, y_train)

# Fazer previsões
y_pred = rf_model.predict(X_test)

pickle.dump(rf_model, open('model.pkl','wb')) # salvando o modelo